version: "3.1"

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    security_opt:
      - seccomp:unconfined

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    restart: always
    links:
      - mysql:mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - mysql

